In [1]:
# -*- coding: utf-8 -*-
import numpy as np
import random

# 为了可复现
np.random.seed(42)
random.seed(42)

# =========================================================
# （1）预备知识：随机整数 / 字符串拼接 / 数值转字符串
# =========================================================
# 在区间 [1,5] 内随机取出大小为 5x8 的整数矩阵
mat_5x8 = np.random.randint(1, 6, size=(5, 8))
print(mat_5x8)

# 在区间 [1,5] 内随机取出 1 个整数
one_int = np.random.randint(1, 6)
print(one_int)

# 字符串连接
print('数模加油站' + '666')
# Python 也可使用 join 或 f-string
print(''.join(['数模加油站', '666']))

# 数值转字符串与输出
mystr = str(1224)
print("mystr =", mystr)
print(str(1224) + '祝大家平安夜平平安安')

# =========================================================
# （2）代码部分（在成功的条件下的概率）
#   思想：仅根据“是否更换能赢”的逻辑统计两个成功次数，
#   最后用 a/n, b/n 估计两种策略的成功率（与经典 1/3, 2/3 一致）
# =========================================================
n = 100000
a = 0  # 不改变主意时赢的次数
b = 0  # 改变主意时赢的次数

for _ in range(n):
    x = random.randint(1, 3)  # 汽车所在门
    y = random.randint(1, 3)  # 你最初选择的门
    if x == y:
        a += 1      # 不换才赢
    else:
        b += 1      # 换才赢

print(f"蒙特卡罗（仅成功条件）不改变主意的获奖概率 ≈ {a/n:.5f}")
print(f"蒙特卡罗（仅成功条件）改变主意的获奖概率 ≈ {b/n:.5f}")

# =========================================================
# （3）考虑失败情况的代码（无条件概率）
#   思想：额外随机一个 change∈{0,1}（0=不换，1=更换），
#   统计三种结果的相对频率
# =========================================================
n = 100000
a = 0  # 不改变主意时赢
b = 0  # 改变主意时赢
c = 0  # 没有获奖

for _ in range(n):
    x = random.randint(1, 3)
    y = random.randint(1, 3)
    change = random.randint(0, 1)  # 0 不换，1 换

    if x == y:
        if change == 0:
            a += 1   # 不换且中
        else:
            c += 1   # 换则不中
    else:
        if change == 0:
            c += 1   # 不换不中
        else:
            b += 1   # 换且中

print(f"蒙特卡罗（无条件）不改变主意的获奖概率 ≈ {a/n:.5f}")
print(f"蒙特卡罗（无条件）改变主意的获奖概率 ≈ {b/n:.5f}")
print(f"蒙特卡罗（无条件）没有获奖的概率 ≈ {c/n:.5f}")


[[4 5 3 5 5 2 3 3]
 [3 5 4 3 5 2 4 2]
 [4 5 1 4 2 5 4 1]
 [1 3 3 2 4 4 3 4]
 [4 1 3 5 3 5 1 2]]
4
数模加油站666
数模加油站666
mystr = 1224
1224祝大家平安夜平平安安
蒙特卡罗（仅成功条件）不改变主意的获奖概率 ≈ 0.33456
蒙特卡罗（仅成功条件）改变主意的获奖概率 ≈ 0.66544
蒙特卡罗（无条件）不改变主意的获奖概率 ≈ 0.16395
蒙特卡罗（无条件）改变主意的获奖概率 ≈ 0.33390
蒙特卡罗（无条件）没有获奖的概率 ≈ 0.50215
